
modal = [
    {"TIPO_MODAL": "RODOVIARIO", "SIGLA_MODAL": "RO", "R_C_D": "RO_", "OFERRING_TYPE": "TL", "TRANSPORT_MODE": "TL"},
    {"TIPO_MODAL": "FRACIONADO", "SIGLA_MODAL": "FF", "R_C_D": "FF_", "OFERRING_TYPE": "TL", "TRANSPORT_MODE": "TL"},
    {"TIPO_MODAL": "CABOTAGEM", "SIGLA_MODAL": "CB", "R_C_D": "CB_", "OFERRING_TYPE": "VESSEL", "TRANSPORT_MODE": "VESSEL-CO"},
    {"TIPO_MODAL": "AEREO", "SIGLA_MODAL": "AR", "R_C_D": "AR_", "OFERRING_TYPE": "AIR", "TRANSPORT_MODE": "AIR"},
    {"TIPO_MODAL": "CONSOLIDADO", "SIGLA_MODAL": "CO", "R_C_D": "CO_", "OFERRING_TYPE": "TL", "TRANSPORT_MODE": "TL"},
    {"TIPO_MODAL": "DIRETO", "SIGLA_MODAL": "RO", "R_C_D": "RO_", "OFERRING_TYPE": "TL", "TRANSPORT_MODE": "TL"},
    {"TIPO_MODAL": "SPOT", "SIGLA_MODAL": "SP", "R_C_D": "SP_", "OFERRING_TYPE": "TL", "TRANSPORT_MODE": "TL"},
    {"TIPO_MODAL": "REDESPACHO", "SIGLA_MODAL": "RE", "R_C_D": "RE_", "OFERRING_TYPE": "TL", "TRANSPORT_MODE": "TL"}
]

modalDedicado = [
    {"TIPO_MODAL": "ANCRA", "SIGLA_MODAL": "AC", "R_C_D": "AC_", "OFERRING_TYPE": "TL", "TRANSPORT_MODE": "TL"},
    {"TIPO_MODAL": "ESTATICO", "SIGLA_MODAL": "ES", "R_C_D": "ES_", "OFERRING_TYPE": "TL", "TRANSPORT_MODE": "TL"},
    {"TIPO_MODAL": "DINAMICO", "SIGLA_MODAL": "DI", "R_C_D": "DI_", "OFERRING_TYPE": "TL", "TRANSPORT_MODE": "TL"},
    {"TIPO_MODAL": "DUNORTE", "SIGLA_MODAL": "DN", "R_C_D": "DN_", "OFERRING_TYPE": "TL", "TRANSPORT_MODE": "TL"},
    {"TIPO_MODAL": "FROTA", "SIGLA_MODAL": "FT", "R_C_D": "FT_", "OFERRING_TYPE": "TL", "TRANSPORT_MODE": "TL"}
]


unit = [
    {"UNIDADE": "PESO", "UNIDADE_S": "P", "SEQ": "2", "UOM_TYPE": "WEGHT", "CHARGE_BREAK_COMPARATOR": "SHIPMENT.WEIGHT","SIGLAS_UNIDADE":"KG"},
    {"UNIDADE": "VOLUME", "UNIDADE_S": "V", "SEQ": "1", "UOM_TYPE": "VOLUME", "CHARGE_BREAK_COMPARATOR": "SHIPMENT.VOLUME","SIGLAS_UNIDADE":"CUMTR"},
    {"UNIDADE": "PESO_CUBADO", "UNIDADE_S": "P", "SEQ": "2", "UOM_TYPE": "WEGHT", "CHARGE_BREAK_COMPARATOR": "SHIPMENT.WEIGHT","SIGLAS_UNIDADE":"KG"},
    {"UNIDADE": "PESO_CUBADO", "UNIDADE_S": "V", "SEQ": "1", "UOM_TYPE": "VOLUME", "CHARGE_BREAK_COMPARATOR": "SHIPMENT.VOLUME","SIGLAS_UNIDADE":"CUMTR"},
    {"UNIDADE": "FIXO", "UNIDADE_S": "", "SEQ": "3", "UOM_TYPE": "", "CHARGE_BREAK_COMPARATOR": "","SIGLAS_UNIDADE":""},
    {"UNIDADE": "REDE_FARMA", "UNIDADE_S": "N", "SEQ": "1", "UOM_TYPE": "", "CHARGE_BREAK_COMPARATOR": "SHIPMENT.NUMSHIPUNITS","SIGLAS_UNIDADE":""}
]


gris = [
    {"COD": "GRI", "NOME": "GRIS", "POR": "SHIPMENT", "COST_CATEGORY_GID": "ACCESSORIAL", "ACCESSORIAL_CODE": "GRIS","COST_TYPE":"C"}
    
]


custo_fixo = [
    
    {"COD": "CF", 
     "NOME": "CUSTO_FIXO", 
     "POR": "SHIPMENT", 
     "COST_CATEGORY_GID": "FIXED_COST", 
     "ACCESSORIAL_CODE": "FIXED_COST",
     "COST_TYPE":"C"}
    
]

distanceService = [
    {"MODAL": "ANCRA", "RATE_DISTANCE": "TMS_RATE_DISTANCE", "RATE_SERVICE": "TMS_RS_DEDICATED"},
    {"MODAL": "ESTATICO", "RATE_DISTANCE": "TMS_RATE_DISTANCE", "RATE_SERVICE": "TMS_RS_DEDICATED"},
    {"MODAL": "DINAMICO", "RATE_DISTANCE": "TMS_RATE_DISTANCE", "RATE_SERVICE": "TMS_RS_DEDICATED"},
    {"MODAL": "DUNORTE", "RATE_DISTANCE": "TMS_RATE_DISTANCE", "RATE_SERVICE": "TMS_RS_DEDICATED"},
    {"MODAL": "FROTA", "RATE_DISTANCE": "TMS_RATE_DISTANCE", "RATE_SERVICE": "TMS_RS_DEDICATED"},
    {"MODAL": "RODOVIARIO", "RATE_DISTANCE": "TMS_RATE_DISTANCE", "RATE_SERVICE": "TMS_RS_TL"},
    {"MODAL": "FRACIONADO", "RATE_DISTANCE": "TMS_RATE_DISTANCE", "RATE_SERVICE": "TMS_RS_TL"},
    {"MODAL": "FROTA DEDICADA", "RATE_DISTANCE": "TMS_RATE_DISTANCE", "RATE_SERVICE": "TMS_RS_DEDICATED"},
    {"MODAL": "CABOTAGEM", "RATE_DISTANCE": "TMS_RATE_DISTANCE", "RATE_SERVICE": "TMS_RS_VESSEL"},
    {"MODAL": "AEREO", "RATE_DISTANCE": "TMS_RATE_DISTANCE", "RATE_SERVICE": "TMS_RS_AIR"},
    {"MODAL": "CONSOLIDADO", "RATE_DISTANCE": "TMS_RATE_DISTANCE", "RATE_SERVICE": "TMS_RS_TL"},
    {"MODAL": "DIRETO", "RATE_DISTANCE": "TMS_RATE_DISTANCE", "RATE_SERVICE": "TMS_RS_TL"},
    {"MODAL": "SPOT", "RATE_DISTANCE": "TMS_RATE_DISTANCE", "RATE_SERVICE": "TMS_RS_TL"},
    {"MODAL": "REDESPACHO", "RATE_DISTANCE": "TMS_RATE_DISTANCE", "RATE_SERVICE": "TMS_RS_TL"},
    {"MODAL": "SPOT", "RATE_DISTANCE": "TMS_RATE_DISTANCE", "RATE_SERVICE": "TMS_RS_VESSEL"}
]

infos = [
    {
        "F_FRACIONADA": "FF_",
        "F_DEDICADA": "FD_",
        "CABOTAGEM": "CB_",
        "RODOVIARIO": "RO_",
        "REDESPACHO": "RE_",
        "SPOT": "SP_",
        "AIR": "AIR",
        "AEREA": "AR_",
        "BR": "BR",
        "BRL": "BRL",
        "TL": "TL",
        "RATE_DISTANCE": "RATE_DISTANCE",
        "RATE_SERVICE": "RATE_SERVICE",
        "INTERVALO": "2018-2999",
        "DEFAULT": "DEFAULT",
        "RATE_GEO_REFNUM_QUAL_GID": "TRANSPORT_MODE",
        "SHIPMENT": "SHIPMENT",
        "zone_value1": "zone_value1_",
        "EXPRESSO": "EXPRESS",
        "LOCATION": "LOCATION",
        "DAILY": "DAILY",
        "EQUIPMENT_TYPE": "DEDICATED",
        "MONTHLY": "MONTHLY"
    }
]

refnum = [  
    {
        "TIPO_TARIFA": "TIPO_TARIFA",
        "OPERACAO": "OPERACAO",
        "TRANSPORTADORA": "TRANSPORTADORA",
        "DESC_ORIGEM": "DESC_ORIGEM",
        "DESC_DESTINO": "DESC_DESTINO",
        "ID_ORIGEM": "ID_ORIGEM",
        "ID_DESTINO": "ID_DESTINO",
        "TIPO_DEDICADA": "TIPO_DEDICADA",
        "PORC_GRIS": "GRIS",
        "PORC_AD_VALOREM": "AD_VALOREM"
    }
]

delivery_stop_constraint = [
    {"TIPO_DE_TARIFA": "FROTA DEDICADA", "STOPS": 1, "PICKUP_STOPS_CONSTRAINT": 1},
    {"TIPO_DE_TARIFA": "RODOVIARIO", "STOPS": 1, "PICKUP_STOPS_CONSTRAINT": 1},
    {"TIPO_DE_TARIFA": "AEREO", "STOPS": 1, "PICKUP_STOPS_CONSTRAINT": 1},
    {"TIPO_DE_TARIFA": "CABOTAGEM", "STOPS": 1, "PICKUP_STOPS_CONSTRAINT": 1},
    {"TIPO_DE_TARIFA": "FRACIONADO", "STOPS": 1, "PICKUP_STOPS_CONSTRAINT": 1},
    {"TIPO_DE_TARIFA": "ANCRA", "STOPS": 1, "PICKUP_STOPS_CONSTRAINT": 1},
    {"TIPO_DE_TARIFA": "ESTATICO", "STOPS": 1, "PICKUP_STOPS_CONSTRAINT": 1},
    {"TIPO_DE_TARIFA": "DINAMICO", "STOPS": 1, "PICKUP_STOPS_CONSTRAINT": 1},
    {"TIPO_DE_TARIFA": "DUNORTE", "STOPS": 1, "PICKUP_STOPS_CONSTRAINT": 1},
    {"TIPO_DE_TARIFA": "FROTA", "STOPS": 1, "PICKUP_STOPS_CONSTRAINT": 1},
    {"TIPO_DE_TARIFA": "CONSOLIDADO", "STOPS": 2, "PICKUP_STOPS_CONSTRAINT": 1},
    {"TIPO_DE_TARIFA": "DIRETO", "STOPS": 1, "PICKUP_STOPS_CONSTRAINT": 1},
    {"TIPO_DE_TARIFA": "SPOT", "STOPS": 1, "PICKUP_STOPS_CONSTRAINT": 1},
    {"TIPO_DE_TARIFA": "REDESPACHO", "STOPS": 1, "PICKUP_STOPS_CONSTRAINT": 1}
]

tarifas_shipment = [
    {"TIPO_DE_TARIFA": "DIRETO", "SHIPMENT": "SHIPMENT"},
    {"TIPO_DE_TARIFA": "REDESPACHO", "SHIPMENT": "SHIPMENT"},
    {"TIPO_DE_TARIFA": "RODOVIARIO", "SHIPMENT": "SHIPMENT"},
    {"TIPO_DE_TARIFA": "FRACIONADO", "SHIPMENT": "SHIPMENT"},
    {"TIPO_DE_TARIFA": "FROTA DEDICADA", "SHIPMENT": "SHIPMENT.LOADEDDISTANCE"},
    {"TIPO_DE_TARIFA": "CABOTAGEM", "SHIPMENT": "SHIPMENT"},
    {"TIPO_DE_TARIFA": "SPOT", "SHIPMENT": "SHIPMENT"},
    {"TIPO_DE_TARIFA": "AEREO", "SHIPMENT": "SHIPMENT"},
    {"TIPO_DE_TARIFA": "CONSOLIDADO", "SHIPMENT": "SHIPMENT.SEL_NUMSTOPS"},
]

parada = [
    "ST",
    "ENCARGO_DE_PARADA",
    "SHIPMENT",
    "ACCESSORIAL",
    "STOP-OFF_CHARGE",
    "C"
]

pedagio = [
    "PD",
    "PEDAGIO",
    "SHIPMENT",
    "ACCESSORIAL",
    "TOLL",
    "C"
]

advalorem = [
    "AD", 
    "AD VALOREM", 
    "SHIPMENT", 
    "ACCESSORIAL", 
    "AD_VALOREM",
    "C" 
]

acessorial = [
    "PRIO_H",
    "PRIO_L",
    "PRIORITY",
    "DIRECT_W_COST",
    "DIRECT_W_COST_TRIANG"
]


eixo = [
    {
        "COD": "EXT",
        "NOME": "AXIS",
        "POR": "SHIPMENT",
        "LEFT_OPERAND1": "SHIPMENT.SHIPUNITS.FLEXCOMMQUAL",
        "OPER1_GID": "EQ",
        "LOW_VALUE1": "COMMOD",
        "AND_OR1": "A",
        "LEFT_OPERAND2": "SHIPMENT.SEL_NUMSHIPUNITS",
        "OPER2_GID": "GT",
        "LOW_VALUE2": "30",
        "AND_OR2": "A",
        "LEFT_OPERAND3": "SHPMENT.SHIPUNITS.LINES.COMMODITY",
        "OPR3_GID": "EQ",
        "LOW_VALUE3": "NTR.ZPRE",
        "COST_CATEGORY_GID": "ACCESSORIAL",
        "ACESSORIAL_CODE": "EXTRA_AXIS",
        "COST_TYPE": "C"
    }
]

ajudante = [
    {
        "COD": "AJU",
        "NOME": "AJUDANTE",
        "POR": "SHIPMENT.STOPS.REFNUMS.NUMBER_VALUE",
        "LEFT_OPERAND1": "SHIPMENT.STOPS.REFNUMS.REFNUM_QUAL",
        "OPER1_GID": "EQ",
        "LOW_VALUE1": "NTR.AJUDANTE",
        "COST_CATEGORY_GID": "ACCESSORIAL",
        "ACCESSORIAL_CODE": "HELP_COST",
        "COST_TYPE": "C",
        "COD_SHIPMENT": "SHIPMENT"
    }
]


farma = [
    {"COD_TRANSPORTADORA": "T300", "REDE_FARMA": "PJ1299", "QTD_MINIMA": 0, "QTD_MAXIMA": 50, "TOTAL_DE_AJUDANTES": 1, "VALOR_FARMA": 200},
    {"COD_TRANSPORTADORA": "T300", "REDE_FARMA": "PJ1360", "QTD_MINIMA": 0, "QTD_MAXIMA": 50, "TOTAL_DE_AJUDANTES": 1, "VALOR_FARMA": 200},
    {"COD_TRANSPORTADORA": "T300", "REDE_FARMA": "PJ1441", "QTD_MINIMA": 0, "QTD_MAXIMA": 50, "TOTAL_DE_AJUDANTES": 1, "VALOR_FARMA": 200},
    {"COD_TRANSPORTADORA": "T300", "REDE_FARMA": "PJ1442", "QTD_MINIMA": 0, "QTD_MAXIMA": 50, "TOTAL_DE_AJUDANTES": 1, "VALOR_FARMA": 200},
    {"COD_TRANSPORTADORA": "T300", "REDE_FARMA": "PJ1443", "QTD_MINIMA": 0, "QTD_MAXIMA": 50, "TOTAL_DE_AJUDANTES": 1, "VALOR_FARMA": 200},
    {"COD_TRANSPORTADORA": "T300", "REDE_FARMA": "PJ1444", "QTD_MINIMA": 0, "QTD_MAXIMA": 50, "TOTAL_DE_AJUDANTES": 1, "VALOR_FARMA": 200},
    {"COD_TRANSPORTADORA": "T300", "REDE_FARMA": "PJ1445", "QTD_MINIMA": 0, "QTD_MAXIMA": 50, "TOTAL_DE_AJUDANTES": 1, "VALOR_FARMA": 200},
    {"COD_TRANSPORTADORA": "T300", "REDE_FARMA": "PJ1546", "QTD_MINIMA": 0, "QTD_MAXIMA": 50, "TOTAL_DE_AJUDANTES": 1, "VALOR_FARMA": 200},
    {"COD_TRANSPORTADORA": "T995", "REDE_FARMA": "PJ1547", "QTD_MINIMA": 0, "QTD_MAXIMA": 50, "TOTAL_DE_AJUDANTES": 1, "VALOR_FARMA": 200},
    {"COD_TRANSPORTADORA": "T300", "REDE_FARMA": "PJ1568", "QTD_MINIMA": 0, "QTD_MAXIMA": 50, "TOTAL_DE_AJUDANTES": 1, "VALOR_FARMA": 200},
    {"COD_TRANSPORTADORA": "T300", "REDE_FARMA": "PJ1569", "QTD_MINIMA": 0, "QTD_MAXIMA": 50, "TOTAL_DE_AJUDANTES": 1, "VALOR_FARMA": 200},
    {"COD_TRANSPORTADORA": "T300", "REDE_FARMA": "PJ1573", "QTD_MINIMA": 0, "QTD_MAXIMA": 50, "TOTAL_DE_AJUDANTES": 1, "VALOR_FARMA": 200},
    {"COD_TRANSPORTADORA": "T300", "REDE_FARMA": "PJ1600", "QTD_MINIMA": 0, "QTD_MAXIMA": 50, "TOTAL_DE_AJUDANTES": 1, "VALOR_FARMA": 200},
    {"COD_TRANSPORTADORA": "T300", "REDE_FARMA": "PJ1601", "QTD_MINIMA": 0, "QTD_MAXIMA": 50, "TOTAL_DE_AJUDANTES": 1, "VALOR_FARMA": 200},
    {"COD_TRANSPORTADORA": "T300", "REDE_FARMA": "PJ1612", "QTD_MINIMA": 0, "QTD_MAXIMA": 50, "TOTAL_DE_AJUDANTES": 1, "VALOR_FARMA": 200},
]

aux_geo_cost_c = [
    {
        "OPER1_GID": "EQ",
        "LEFT_OPERAND1": "SHIPMENT.STOPS.SHIPUNITS.ACTIVITY",
        "LOW_VALUE1": "P",
        "AND_OR1": "A",
        "OPER2_GID": "EQ",
        "LEFT_OPERAND2": "SHIPMENT.STOPS.STOP_NUMBER",
        "LOW_VALUE2": "",
        "AND_OR2": "S",
        "OPER3_GID": "EQ",
        "LEFT_OPERAND3": "SHIPMENT.STOPS.REFNUMS.REFNUM_QUAL",
        "LOW_VALUE3": "NTR.STOP_TYPE",
        "AND_OR3": "A",
        "OPER4_GID": "EQ",
        "LEFT_OPERAND4": "SHIPMENT.STOPS.REFNUMS.REFNUM_VALUE",
        "LOW_VALUE4": "",
        "CHARGE_CURRENCY_GID": "BRL",
        "CHARGE_UNIT_COUNT": "1",
        "CHARGE_MULTIPLIER": "SHIPMENT.SEL_NUMSTOPS",
        "COST_TYPE": "C"
    }
]

aux_geo_cost_e = [
    {
        "OPER1_GID": "EQ",
        "LEFT_OPERAND1": "SHIPMENT.STOPS.STOP_NUMBER",
        "LOW_VALUE1": "",
        "AND_OR1": "A",
        "OPER2_GID": "EQ",
        "LEFT_OPERAND2": "SHIPMENT.STOPS.REFNUMS.REFNUM_VALUE",
        "LOW_VALUE2": "",
        "AND_OR2": "A",
        "OPER3_GID": "EQ",
        "LEFT_OPERAND3": "SHIPMENT.STOPS.SHIPUNITS.ACTIVITY",
        "LOW_VALUE3": "D",
        "AND_OR3": "S",
        "OPER4_GID": "EQ",
        "LEFT_OPERAND4": "SHIPMENT.STOPS.REFNUMS.REFNUM_QUAL",
        "LOW_VALUE4": "NTR.STOP_TYPE",
        "CHARGE_CURRENCY_GID": "BRL",
        "CHARGE_UNIT_COUNT": "1",
        "CHARGE_MULTIPLIER": "SHIPMENT.SEL_NUMSTOPS",
        "COST_TYPE": "C"
    }
]



aux_help = [
    {
        "OPER3_GID": "EQ",
        "LEFT_OPERAND3": "SHIPMENT.STOPS.REFNUMS.REFNUM_QUAL",
        "LOW_VALUE3": "NTR.AJUDANTE",
        "AND_OR3": "S",
        "OPER4_GID": "EQ",
        "LEFT_OPERAND4": "SHIPMENT.STOPS.REFNUMS.REFNUM_VALUE",
        "LOW_VALUE4": "",
        "CHARGE_CURRENCY_GID": "BRL",
        "CHARGE_UNIT_COUNT": "1",
        "CHARGE_MULTIPLIER": "SHIPMENT.SEL_NUMSTOPS",
        "COST_TYPE": "C"
    }
]

aux_geo_cost_mc = [
    {
        "OPER1_GID": "EQ",
        "LEFT_OPERAND1": "SHIPMENT.CMTOURPARTICIPATION",
        "LOW_VALUE1": "TRUE",
        "AND_OR1": "A",
        "OPER2_GID": "GT",
        "LEFT_OPERAND2": "SHIPMENT.CMTOURPOSITION",
        "LOW_VALUE2": "1",
        "AND_OR2": "",
        "OPER3_GID": "",
        "LEFT_OPERAND3": "",
        "LOW_VALUE3": "",
        "AND_OR3": "",
        "OPER4_GID": "",
        "LEFT_OPERAND4": "",
        "LOW_VALUE4": "",
        "CHARGE_CURRENCY_GID": "",
        "CHARGE_UNIT_COUNT": "1",
        "CHARGE_MULTIPLIER": "",
        "COST_TYPE": "D",
        "CHARGE_ACTION": "D",
        "COST_CATEGORY_GID": "NTR/BR.CONTINUOUS_MOVE_DISCOUNT"
    }
]

aux_geo_cost_desc_entrega = [
    {
        "SEQ1": [31,32,33,34,35],
        "SEQ2": [41,42,43,44,45],
        "SEQ3": [51,52,53,54,55],
        "SEQ4": [61,62,63,64,65],
        "OPER1_GID": "EQ",
        "LEFT_OPERAND1": "SHIPMENT.NUMSTOPS",
        "LOW_VALUE1": ["2","3","4","5","6"],
        "AND_OR1": "A",
        "OPER2_GID": "EQ",
        "LEFT_OPERAND2": "SHIPMENT.STOPS.STOP_NUMBER",
        "LOW_VALUE2": ["2","3","4","5","6"],
        "AND_OR2": "S",
        "OPER3_GID": "EQ",
        "LEFT_OPERAND3": "SHIPMENT.STOPS.REFNUMS.REFNUM_QUAL",
        "LOW_VALUE3": "NTR.STOP_TYPE",
        "AND_OR3": "A",
        "OPER4_GID": "EQ",
        "LEFT_OPERAND4": "SHIPMENT.STOPS.REFNUMS.REFNUM_VALUE",
        "LOW_VALUE4": "",
        "CHARGE_CURRENCY_GID": "BRL",
        "CHARGE_UNIT_COUNT": "1",
        "CHARGE_MULTIPLIER": "SHIPMENT",
        "COST_TYPE": "C"
    }
]

custo_consolidado = [
    {
        "RATE_GEO_COST_SEQ": 3,
        "CHARGE_CURRENCY_GID": "BRL",
        "CHARGE_UNIT_COUNT": 1,
        "CHARGE_MULTIPLIER": "SHIPMENT",
        "CHARGE_STOP": "STOP",
        "COST_TYPE": "C"
    }
]

repaletizacao = [
    {
        "COD": "RTZ",
        "NOME": "REPALETIZACAO",
        "POR": "SHIPMENT",
        "COST_CATEGORY_GID": "ACCESSORIAL",
        "ACCESSORIAL_CODE": "FARMA_PALLET",
        "LEFT_OPERAND1": "SHIPMENT.ORDERS.ORREFNUMS.REFNUM_QUAL",
        "OPER1_GID": "EQ",
        "LOW_VALUE1": "ORDER_TYPE",
        "AND_OR1": "A",
        "LEFT_OPERAND2": "SHIPMENT.ORDERS.ORREFNUMS.REFNUM_VALUE",
        "OPER2_GID": "EQ",
        "LOW_VALUE2": "ZFAM",
        "AND_OR2": "O",
        "LEFT_OPERAND3": "SHIPMENT.ORDERS.ORREFNUMS.REFNUM_VALUE",
        "CHARGE_MULTIPLIER": "SHIPMENT.SEL_NUMSHIPUNITS",
        "LOW_VALUE3": "ZFAR",
        "OPER3_GID": "EQ",
        "CHARGE_AMOUNT_GID": "BRL",
        "CHARGE_UNIT_COUNT": 1,
        "CHARGE_ACTION": "A",
        "CHARGE_TYPE": "B",
        "USE_DEFAULTS": "N",
        "CHARGE_MULTIPLIER_OPTION": "A",
        "IS_FILED_AS_TARIFF": "N",
        "COST_TYPE": "C",
        "IS_ACTIVE": "Y"
    }
]

domain = ["NTR/BR", "NTR/BR.", "NTR."]

zone = ["ZONE1",  "Z1"]